name: lentera
description: "LENTERA is an innovative AI-powered mental health app offering real-time voice and text counseling, mood tracking, and professional booking, all designed to illuminate your path to well-being."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  image_picker: '>=1.1.2'
  flutter_markdown: 0.7.7+1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0
  dio: ^5.0.0
  web_socket_channel: ^3.0.0
  flutter_sound: ^9.0.0
  record: '>=5.1.2'
  supabase_flutter: '>=1.10.0'
  shared_preferences: ^2.0.0
  intl: 0.20.2
  fl_chart: 0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
